02-Jun-23 19:29:08 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 19:29:08 - root - INFO - Using queue client rabbitmq - queue_client.py - 162 - get_client
02-Jun-23 19:29:08 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 19:29:08 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 19:29:08 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_VHOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 19:29:08 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_USERNAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 19:29:08 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_PASSWORD is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 19:29:08 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0) - connection_workflow.py - 179 - start
02-Jun-23 19:29:08 - pika.adapters.utils.io_services_utils - ERROR - Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 56081, 0, 0)>; error=61 (Connection refused) - io_services_utils.py - 349 - _on_writable
02-Jun-23 19:29:08 - pika.adapters.utils.connection_workflow - ERROR - TCP Connection attempt failed: ConnectionRefusedError(61, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0)) - connection_workflow.py - 375 - _on_tcp_connection_done
02-Jun-23 19:29:08 - pika.adapters.utils.connection_workflow - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(61, 'Connection refused') - connection_workflow.py - 291 - _report_completion_and_cleanup
02-Jun-23 19:29:08 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672) - connection_workflow.py - 179 - start
02-Jun-23 19:29:08 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56082), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 345 - _on_writable
02-Jun-23 19:29:08 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x107f061d0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x107f061d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>). - connection_workflow.py - 428 - _on_transport_establishment_done
02-Jun-23 19:29:08 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x107f061d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 293 - _report_completion_and_cleanup
02-Jun-23 19:29:08 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x107f061d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 725 - _report_completion_and_cleanup
02-Jun-23 19:29:08 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x107f061d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - blocking_connection.py - 453 - _create_connection
02-Jun-23 19:29:08 - pika.adapters.blocking_connection - INFO - Created channel=1 - blocking_connection.py - 1264 - __init__
02-Jun-23 19:29:08 - root - INFO - Connected to queue todo_queue at localhost:5672 - queue_client.py - 90 - connect
02-Jun-23 19:29:09 - root - INFO - List ID: 647367960a35139ab08f73e3, List Name: TODO - trello_client.py - 158 - get_list_id
02-Jun-23 19:32:00 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 19:32:00 - root - INFO - Using queue client rabbitmq - queue_client.py - 162 - get_client
02-Jun-23 19:32:00 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 19:32:00 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 19:32:00 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_VHOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 19:32:00 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_USERNAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 19:32:00 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_PASSWORD is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 19:32:00 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0) - connection_workflow.py - 179 - start
02-Jun-23 19:32:00 - pika.adapters.utils.io_services_utils - ERROR - Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 56153, 0, 0)>; error=61 (Connection refused) - io_services_utils.py - 349 - _on_writable
02-Jun-23 19:32:00 - pika.adapters.utils.connection_workflow - ERROR - TCP Connection attempt failed: ConnectionRefusedError(61, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0)) - connection_workflow.py - 375 - _on_tcp_connection_done
02-Jun-23 19:32:00 - pika.adapters.utils.connection_workflow - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(61, 'Connection refused') - connection_workflow.py - 291 - _report_completion_and_cleanup
02-Jun-23 19:32:00 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672) - connection_workflow.py - 179 - start
02-Jun-23 19:32:00 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56154), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 345 - _on_writable
02-Jun-23 19:32:00 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10a602230>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10a602230> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>). - connection_workflow.py - 428 - _on_transport_establishment_done
02-Jun-23 19:32:00 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10a602230> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 293 - _report_completion_and_cleanup
02-Jun-23 19:32:00 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10a602230> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 725 - _report_completion_and_cleanup
02-Jun-23 19:32:00 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10a602230> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - blocking_connection.py - 453 - _create_connection
02-Jun-23 19:32:00 - pika.adapters.blocking_connection - INFO - Created channel=1 - blocking_connection.py - 1264 - __init__
02-Jun-23 19:32:00 - root - INFO - Connected to queue todo_queue at localhost:5672 - queue_client.py - 90 - connect
02-Jun-23 19:32:01 - root - INFO - List ID: 647367960a35139ab08f73e3, List Name: TODO - trello_client.py - 158 - get_list_id
02-Jun-23 19:32:08 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 52 - webhook
02-Jun-23 19:32:09 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 52 - webhook
02-Jun-23 19:32:16 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 52 - webhook
02-Jun-23 19:33:08 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 19:33:08 - root - INFO - Using queue client rabbitmq - queue_client.py - 162 - get_client
02-Jun-23 19:33:08 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 19:33:08 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 19:33:08 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_VHOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 19:33:08 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_USERNAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 19:33:08 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_PASSWORD is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 19:33:08 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0) - connection_workflow.py - 179 - start
02-Jun-23 19:33:08 - pika.adapters.utils.io_services_utils - ERROR - Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 56255, 0, 0)>; error=61 (Connection refused) - io_services_utils.py - 349 - _on_writable
02-Jun-23 19:33:08 - pika.adapters.utils.connection_workflow - ERROR - TCP Connection attempt failed: ConnectionRefusedError(61, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0)) - connection_workflow.py - 375 - _on_tcp_connection_done
02-Jun-23 19:33:08 - pika.adapters.utils.connection_workflow - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(61, 'Connection refused') - connection_workflow.py - 291 - _report_completion_and_cleanup
02-Jun-23 19:33:08 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672) - connection_workflow.py - 179 - start
02-Jun-23 19:33:08 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 56256), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 345 - _on_writable
02-Jun-23 19:33:08 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x105b02200>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x105b02200> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>). - connection_workflow.py - 428 - _on_transport_establishment_done
02-Jun-23 19:33:08 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x105b02200> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 293 - _report_completion_and_cleanup
02-Jun-23 19:33:08 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x105b02200> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 725 - _report_completion_and_cleanup
02-Jun-23 19:33:08 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x105b02200> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - blocking_connection.py - 453 - _create_connection
02-Jun-23 19:33:08 - pika.adapters.blocking_connection - INFO - Created channel=1 - blocking_connection.py - 1264 - __init__
02-Jun-23 19:33:08 - root - INFO - Connected to queue todo_queue at localhost:5672 - queue_client.py - 90 - connect
02-Jun-23 19:33:09 - root - INFO - List ID: 647367960a35139ab08f73e3, List Name: TODO - trello_client.py - 158 - get_list_id
02-Jun-23 19:33:16 - root - ERROR - Message was not sent - queue_client.py - 111 - produce
02-Jun-23 19:33:16 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 52 - webhook
02-Jun-23 19:33:26 - root - ERROR - Message was not sent - queue_client.py - 111 - produce
02-Jun-23 19:33:26 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 52 - webhook
02-Jun-23 19:33:38 - root - ERROR - Message was not sent - queue_client.py - 111 - produce
02-Jun-23 19:33:38 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 52 - webhook
02-Jun-23 19:33:44 - root - ERROR - Message was not sent - queue_client.py - 111 - produce
02-Jun-23 19:33:44 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 52 - webhook
02-Jun-23 22:38:47 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:47 - root - INFO - Using queue client rabbitmq - queue_client.py - 162 - get_client
02-Jun-23 22:38:47 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:47 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:47 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_VHOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:47 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_USERNAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:47 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_PASSWORD is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:47 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0) - connection_workflow.py - 179 - start
02-Jun-23 22:38:47 - pika.adapters.utils.io_services_utils - ERROR - Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 57612, 0, 0)>; error=61 (Connection refused) - io_services_utils.py - 349 - _on_writable
02-Jun-23 22:38:47 - pika.adapters.utils.connection_workflow - ERROR - TCP Connection attempt failed: ConnectionRefusedError(61, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0)) - connection_workflow.py - 375 - _on_tcp_connection_done
02-Jun-23 22:38:47 - pika.adapters.utils.connection_workflow - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(61, 'Connection refused') - connection_workflow.py - 291 - _report_completion_and_cleanup
02-Jun-23 22:38:47 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672) - connection_workflow.py - 179 - start
02-Jun-23 22:38:47 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 57613), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 345 - _on_writable
02-Jun-23 22:38:47 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1055fa230>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1055fa230> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>). - connection_workflow.py - 428 - _on_transport_establishment_done
02-Jun-23 22:38:47 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1055fa230> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 293 - _report_completion_and_cleanup
02-Jun-23 22:38:47 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1055fa230> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 725 - _report_completion_and_cleanup
02-Jun-23 22:38:47 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1055fa230> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - blocking_connection.py - 453 - _create_connection
02-Jun-23 22:38:47 - pika.adapters.blocking_connection - INFO - Created channel=1 - blocking_connection.py - 1264 - __init__
02-Jun-23 22:38:47 - root - INFO - Connected to queue todo_queue at localhost:5672 - queue_client.py - 90 - connect
02-Jun-23 22:38:50 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:50 - root - INFO - Using queue client rabbitmq - queue_client.py - 162 - get_client
02-Jun-23 22:38:50 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:50 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:50 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_VHOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:50 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_USERNAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:50 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_PASSWORD is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:38:50 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0) - connection_workflow.py - 179 - start
02-Jun-23 22:38:50 - pika.adapters.utils.io_services_utils - ERROR - Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 57626, 0, 0)>; error=61 (Connection refused) - io_services_utils.py - 349 - _on_writable
02-Jun-23 22:38:50 - pika.adapters.utils.connection_workflow - ERROR - TCP Connection attempt failed: ConnectionRefusedError(61, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0)) - connection_workflow.py - 375 - _on_tcp_connection_done
02-Jun-23 22:38:50 - pika.adapters.utils.connection_workflow - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(61, 'Connection refused') - connection_workflow.py - 291 - _report_completion_and_cleanup
02-Jun-23 22:38:50 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672) - connection_workflow.py - 179 - start
02-Jun-23 22:38:50 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 57627), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 345 - _on_writable
02-Jun-23 22:38:50 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x104ff6230>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x104ff6230> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>). - connection_workflow.py - 428 - _on_transport_establishment_done
02-Jun-23 22:38:50 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x104ff6230> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 293 - _report_completion_and_cleanup
02-Jun-23 22:38:50 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x104ff6230> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 725 - _report_completion_and_cleanup
02-Jun-23 22:38:50 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x104ff6230> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - blocking_connection.py - 453 - _create_connection
02-Jun-23 22:38:50 - pika.adapters.blocking_connection - INFO - Created channel=1 - blocking_connection.py - 1264 - __init__
02-Jun-23 22:38:50 - root - INFO - Connected to queue todo_queue at localhost:5672 - queue_client.py - 90 - connect
02-Jun-23 22:38:52 - root - INFO - List ID: 647367960a35139ab08f73e3, List Name: TODO - trello_client.py - 158 - get_list_id
02-Jun-23 22:41:51 - pika.adapters.utils.io_services_utils - ERROR - Socket EOF; <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 57627), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 796 - _consume
02-Jun-23 22:41:51 - pika.adapters.base_connection - ERROR - Transport indicated EOF. - base_connection.py - 445 - _proto_eof_received
02-Jun-23 22:41:51 - pika.adapters.utils.io_services_utils - INFO - protocol.eof_received() elected to close: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 57627), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 1063 - _on_socket_readable
02-Jun-23 22:41:51 - pika.adapters.utils.io_services_utils - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 57627), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 904 - _initiate_abort
02-Jun-23 22:41:51 - pika.adapters.utils.io_services_utils - INFO - Deactivating transport: state=1; <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 57627), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 869 - _deactivate
02-Jun-23 22:41:51 - pika.adapters.base_connection - ERROR - connection_lost: StreamLostError: ('Transport indicated EOF',) - base_connection.py - 428 - _proto_connection_lost
02-Jun-23 22:41:51 - pika.connection - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=StreamLostError: ('Transport indicated EOF',); pending-error=None - connection.py - 2017 - _on_stream_terminated
02-Jun-23 22:41:51 - pika.connection - INFO - Stack terminated due to StreamLostError: ('Transport indicated EOF',) - connection.py - 2086 - _on_stream_terminated
02-Jun-23 22:41:51 - pika.adapters.utils.io_services_utils - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 57627), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 882 - _close_and_finalize
02-Jun-23 22:41:51 - pika.adapters.blocking_connection - ERROR - Unexpected connection close detected: StreamLostError: ('Transport indicated EOF',) - blocking_connection.py - 521 - _flush_output
02-Jun-23 22:41:51 - root - ERROR - Stream error: Transport indicated EOF - queue_client.py - 117 - produce
02-Jun-23 22:41:51 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0) - connection_workflow.py - 179 - start
02-Jun-23 22:41:51 - pika.adapters.utils.io_services_utils - ERROR - Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 57670, 0, 0)>; error=61 (Connection refused) - io_services_utils.py - 349 - _on_writable
02-Jun-23 22:41:51 - pika.adapters.utils.connection_workflow - ERROR - TCP Connection attempt failed: ConnectionRefusedError(61, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0)) - connection_workflow.py - 375 - _on_tcp_connection_done
02-Jun-23 22:41:51 - pika.adapters.utils.connection_workflow - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(61, 'Connection refused') - connection_workflow.py - 291 - _report_completion_and_cleanup
02-Jun-23 22:41:51 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672) - connection_workflow.py - 179 - start
02-Jun-23 22:41:51 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 57671), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 345 - _on_writable
02-Jun-23 22:41:51 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x105209ea0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x105209ea0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>). - connection_workflow.py - 428 - _on_transport_establishment_done
02-Jun-23 22:41:51 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x105209ea0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 293 - _report_completion_and_cleanup
02-Jun-23 22:41:51 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x105209ea0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 725 - _report_completion_and_cleanup
02-Jun-23 22:41:51 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x105209ea0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - blocking_connection.py - 453 - _create_connection
02-Jun-23 22:41:51 - pika.adapters.blocking_connection - INFO - Created channel=1 - blocking_connection.py - 1264 - __init__
02-Jun-23 22:41:51 - root - INFO - Connected to queue todo_queue at localhost:5672 - queue_client.py - 90 - connect
02-Jun-23 22:41:51 - root - ERROR - Message was not sent - queue_client.py - 111 - produce
02-Jun-23 22:41:51 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 52 - webhook
02-Jun-23 22:41:52 - root - ERROR - Message was not sent - queue_client.py - 111 - produce
02-Jun-23 22:41:52 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 52 - webhook
02-Jun-23 22:41:53 - root - ERROR - Message was not sent - queue_client.py - 111 - produce
02-Jun-23 22:41:53 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 52 - webhook
02-Jun-23 22:42:08 - root - ERROR - Message was not sent - queue_client.py - 111 - produce
02-Jun-23 22:42:08 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 52 - webhook
02-Jun-23 22:42:09 - root - ERROR - Message was not sent - queue_client.py - 111 - produce
02-Jun-23 22:42:09 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 52 - webhook
02-Jun-23 22:42:41 - root - ERROR - Message was not sent - queue_client.py - 111 - produce
02-Jun-23 22:42:41 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 52 - webhook
02-Jun-23 22:42:47 - root - ERROR - Message was not sent - queue_client.py - 111 - produce
02-Jun-23 22:42:47 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 52 - webhook
02-Jun-23 22:43:09 - root - ERROR - Message was not sent - queue_client.py - 111 - produce
02-Jun-23 22:43:09 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 52 - webhook
02-Jun-23 22:45:28 - root - ERROR - Message was not sent - queue_client.py - 111 - produce
02-Jun-23 22:45:31 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 52 - webhook
02-Jun-23 22:45:38 - root - ERROR - Message was not sent - queue_client.py - 111 - produce
02-Jun-23 22:45:39 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 52 - webhook
02-Jun-23 22:47:58 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:47:58 - root - INFO - Using queue client rabbitmq - queue_client.py - 161 - get_client
02-Jun-23 22:47:58 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:47:58 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:47:58 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_VHOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:47:58 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_USERNAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:47:58 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_PASSWORD is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:47:58 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0) - connection_workflow.py - 179 - start
02-Jun-23 22:47:58 - pika.adapters.utils.io_services_utils - ERROR - Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 57780, 0, 0)>; error=61 (Connection refused) - io_services_utils.py - 349 - _on_writable
02-Jun-23 22:47:58 - pika.adapters.utils.connection_workflow - ERROR - TCP Connection attempt failed: ConnectionRefusedError(61, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0)) - connection_workflow.py - 375 - _on_tcp_connection_done
02-Jun-23 22:47:58 - pika.adapters.utils.connection_workflow - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(61, 'Connection refused') - connection_workflow.py - 291 - _report_completion_and_cleanup
02-Jun-23 22:47:58 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672) - connection_workflow.py - 179 - start
02-Jun-23 22:47:58 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 57781), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 345 - _on_writable
02-Jun-23 22:47:58 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10980a350>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10980a350> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>). - connection_workflow.py - 428 - _on_transport_establishment_done
02-Jun-23 22:47:58 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10980a350> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 293 - _report_completion_and_cleanup
02-Jun-23 22:47:58 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10980a350> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 725 - _report_completion_and_cleanup
02-Jun-23 22:47:58 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10980a350> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - blocking_connection.py - 453 - _create_connection
02-Jun-23 22:47:58 - pika.adapters.blocking_connection - INFO - Created channel=1 - blocking_connection.py - 1264 - __init__
02-Jun-23 22:47:58 - root - INFO - Connected to queue todo_queue at localhost:5672 - queue_client.py - 90 - connect
02-Jun-23 22:47:59 - root - INFO - List ID: 647367960a35139ab08f73e3, List Name: TODO - trello_client.py - 158 - get_list_id
02-Jun-23 22:49:02 - root - ERROR - Message was not sent - queue_client.py - 110 - produce
02-Jun-23 22:49:04 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 52 - webhook
02-Jun-23 22:49:48 - root - ERROR - Message was not sent - queue_client.py - 110 - produce
02-Jun-23 22:49:48 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 52 - webhook
02-Jun-23 22:54:55 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:54:55 - root - INFO - Using queue client rabbitmq - queue_client.py - 163 - get_client
02-Jun-23 22:54:55 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:54:55 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:54:55 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_VHOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:54:55 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_USERNAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:54:55 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_PASSWORD is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 22:54:55 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0) - connection_workflow.py - 179 - start
02-Jun-23 22:54:55 - pika.adapters.utils.io_services_utils - ERROR - Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 57995, 0, 0)>; error=61 (Connection refused) - io_services_utils.py - 349 - _on_writable
02-Jun-23 22:54:55 - pika.adapters.utils.connection_workflow - ERROR - TCP Connection attempt failed: ConnectionRefusedError(61, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0)) - connection_workflow.py - 375 - _on_tcp_connection_done
02-Jun-23 22:54:55 - pika.adapters.utils.connection_workflow - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(61, 'Connection refused') - connection_workflow.py - 291 - _report_completion_and_cleanup
02-Jun-23 22:54:55 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672) - connection_workflow.py - 179 - start
02-Jun-23 22:54:55 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 57996), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 345 - _on_writable
02-Jun-23 22:54:55 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1056062c0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1056062c0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>). - connection_workflow.py - 428 - _on_transport_establishment_done
02-Jun-23 22:54:55 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1056062c0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 293 - _report_completion_and_cleanup
02-Jun-23 22:54:55 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1056062c0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 725 - _report_completion_and_cleanup
02-Jun-23 22:54:55 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x1056062c0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - blocking_connection.py - 453 - _create_connection
02-Jun-23 22:54:55 - pika.adapters.blocking_connection - INFO - Created channel=1 - blocking_connection.py - 1264 - __init__
02-Jun-23 22:54:55 - root - INFO - Connected to queue todo_queue at localhost:5672 - queue_client.py - 90 - connect
02-Jun-23 22:54:56 - root - INFO - List ID: 647367960a35139ab08f73e3, List Name: TODO - trello_client.py - 158 - get_list_id
02-Jun-23 22:55:17 - root - INFO - Message was sent to queue todo_queue successfully. - queue_client.py - 109 - produce
02-Jun-23 22:56:06 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 52 - webhook
02-Jun-23 22:56:44 - root - INFO - Message was sent to queue todo_queue successfully. - queue_client.py - 109 - produce
02-Jun-23 22:56:44 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 52 - webhook
02-Jun-23 23:51:29 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:51:29 - root - WARNING - Warning: Optional environment variable LOG_LEVEL is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:51:29 - root - WARNING - Warning: Optional environment variable LOG_FILE is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:51:29 - root - ERROR - Must specify queue name - queue_client.py - 51 - __init__
02-Jun-23 23:54:40 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:54:40 - root - WARNING - Warning: Optional environment variable LOG_LEVEL is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:54:40 - root - WARNING - Warning: Optional environment variable LOG_FILE is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:54:40 - root - WARNING - Warning: Optional environment variable QUEUE_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:54:40 - root - WARNING - Warning: Optional environment variable QUEUE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:54:40 - root - WARNING - Warning: Optional environment variable QUEUE_PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:54:40 - root - WARNING - Warning: Optional environment variable QUEUE_VHOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:54:40 - root - WARNING - Warning: Optional environment variable QUEUE_USERNAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:54:40 - root - WARNING - Warning: Optional environment variable QUEUE_PASSWORD is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:54:40 - root - WARNING - Warning: Optional environment variable HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:54:40 - root - WARNING - Warning: Optional environment variable PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:54:40 - root - INFO - Using queue client rabbitmq - queue_client.py - 145 - get_client
02-Jun-23 23:54:40 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0) - connection_workflow.py - 179 - start
02-Jun-23 23:54:40 - pika.adapters.utils.io_services_utils - ERROR - Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 58995, 0, 0)>; error=61 (Connection refused) - io_services_utils.py - 349 - _on_writable
02-Jun-23 23:54:40 - pika.adapters.utils.connection_workflow - ERROR - TCP Connection attempt failed: ConnectionRefusedError(61, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0)) - connection_workflow.py - 375 - _on_tcp_connection_done
02-Jun-23 23:54:40 - pika.adapters.utils.connection_workflow - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(61, 'Connection refused') - connection_workflow.py - 291 - _report_completion_and_cleanup
02-Jun-23 23:54:40 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672) - connection_workflow.py - 179 - start
02-Jun-23 23:54:40 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 58996), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 345 - _on_writable
02-Jun-23 23:54:40 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x107bf2140>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x107bf2140> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>). - connection_workflow.py - 428 - _on_transport_establishment_done
02-Jun-23 23:54:40 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x107bf2140> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 293 - _report_completion_and_cleanup
02-Jun-23 23:54:40 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x107bf2140> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 725 - _report_completion_and_cleanup
02-Jun-23 23:54:40 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x107bf2140> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - blocking_connection.py - 453 - _create_connection
02-Jun-23 23:54:40 - pika.adapters.blocking_connection - INFO - Created channel=1 - blocking_connection.py - 1264 - __init__
02-Jun-23 23:54:40 - root - INFO - Connected to queue flock at localhost:5672 - queue_client.py - 72 - connect
02-Jun-23 23:54:41 - root - INFO - List ID: 647367960a35139ab08f73e3, List Name: TODO - trello_client.py - 143 - get_list_id
02-Jun-23 23:54:49 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:54:49 - root - WARNING - Warning: Optional environment variable LOG_LEVEL is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:54:49 - root - WARNING - Warning: Optional environment variable LOG_FILE is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:54:49 - root - WARNING - Warning: Optional environment variable QUEUE_NAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:54:49 - root - WARNING - Warning: Optional environment variable QUEUE_HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:54:49 - root - WARNING - Warning: Optional environment variable QUEUE_PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:54:49 - root - WARNING - Warning: Optional environment variable QUEUE_VHOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:54:49 - root - WARNING - Warning: Optional environment variable QUEUE_USERNAME is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:54:49 - root - WARNING - Warning: Optional environment variable QUEUE_PASSWORD is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:54:49 - root - WARNING - Warning: Optional environment variable HOST is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:54:49 - root - WARNING - Warning: Optional environment variable PORT is not set - env_checker.py - 26 - check_env_vars
02-Jun-23 23:54:49 - root - INFO - Using queue client rabbitmq - queue_client.py - 145 - get_client
02-Jun-23 23:54:49 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0) - connection_workflow.py - 179 - start
02-Jun-23 23:54:49 - pika.adapters.utils.io_services_utils - ERROR - Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 59019, 0, 0)>; error=61 (Connection refused) - io_services_utils.py - 349 - _on_writable
02-Jun-23 23:54:49 - pika.adapters.utils.connection_workflow - ERROR - TCP Connection attempt failed: ConnectionRefusedError(61, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0)) - connection_workflow.py - 375 - _on_tcp_connection_done
02-Jun-23 23:54:49 - pika.adapters.utils.connection_workflow - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(61, 'Connection refused') - connection_workflow.py - 291 - _report_completion_and_cleanup
02-Jun-23 23:54:49 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672) - connection_workflow.py - 179 - start
02-Jun-23 23:54:49 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 59020), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 345 - _on_writable
02-Jun-23 23:54:49 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x103a06170>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x103a06170> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>). - connection_workflow.py - 428 - _on_transport_establishment_done
02-Jun-23 23:54:49 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x103a06170> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 293 - _report_completion_and_cleanup
02-Jun-23 23:54:49 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x103a06170> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 725 - _report_completion_and_cleanup
02-Jun-23 23:54:49 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x103a06170> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - blocking_connection.py - 453 - _create_connection
02-Jun-23 23:54:49 - pika.adapters.blocking_connection - INFO - Created channel=1 - blocking_connection.py - 1264 - __init__
02-Jun-23 23:54:49 - root - INFO - Connected to queue flock at localhost:5672 - queue_client.py - 72 - connect
02-Jun-23 23:54:50 - root - INFO - List ID: 647367960a35139ab08f73e3, List Name: TODO - trello_client.py - 143 - get_list_id
02-Jun-23 23:55:22 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 53 - webhook
02-Jun-23 23:55:54 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 53 - webhook
03-Jun-23 00:00:42 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:42 - root - WARNING - Warning: Optional environment variable LOG_LEVEL is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:42 - root - WARNING - Warning: Optional environment variable LOG_FILE is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:42 - root - WARNING - Warning: Optional environment variable QUEUE_NAME is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:42 - root - WARNING - Warning: Optional environment variable QUEUE_HOST is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:42 - root - WARNING - Warning: Optional environment variable QUEUE_PORT is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:42 - root - WARNING - Warning: Optional environment variable QUEUE_VHOST is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:42 - root - WARNING - Warning: Optional environment variable QUEUE_USERNAME is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:42 - root - WARNING - Warning: Optional environment variable QUEUE_PASSWORD is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:42 - root - WARNING - Warning: Optional environment variable HOST is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:42 - root - WARNING - Warning: Optional environment variable PORT is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:42 - root - INFO - Using queue client rabbitmq - queue_client.py - 145 - get_client
03-Jun-23 00:00:42 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0) - connection_workflow.py - 179 - start
03-Jun-23 00:00:42 - pika.adapters.utils.io_services_utils - ERROR - Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 59160, 0, 0)>; error=61 (Connection refused) - io_services_utils.py - 349 - _on_writable
03-Jun-23 00:00:42 - pika.adapters.utils.connection_workflow - ERROR - TCP Connection attempt failed: ConnectionRefusedError(61, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0)) - connection_workflow.py - 375 - _on_tcp_connection_done
03-Jun-23 00:00:42 - pika.adapters.utils.connection_workflow - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(61, 'Connection refused') - connection_workflow.py - 291 - _report_completion_and_cleanup
03-Jun-23 00:00:42 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672) - connection_workflow.py - 179 - start
03-Jun-23 00:00:42 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 59161), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 345 - _on_writable
03-Jun-23 00:00:42 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x104cf6140>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x104cf6140> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>). - connection_workflow.py - 428 - _on_transport_establishment_done
03-Jun-23 00:00:42 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x104cf6140> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 293 - _report_completion_and_cleanup
03-Jun-23 00:00:42 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x104cf6140> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 725 - _report_completion_and_cleanup
03-Jun-23 00:00:42 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x104cf6140> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - blocking_connection.py - 453 - _create_connection
03-Jun-23 00:00:42 - pika.adapters.blocking_connection - INFO - Created channel=1 - blocking_connection.py - 1264 - __init__
03-Jun-23 00:00:42 - root - INFO - Connected to queue todo_tickets at localhost:5672 - queue_client.py - 72 - connect
03-Jun-23 00:00:44 - root - INFO - List ID: 647367960a35139ab08f73e3, List Name: TODO - trello_client.py - 143 - get_list_id
03-Jun-23 00:00:52 - root - WARNING - Warning: Optional environment variable FLOCK_QUEUE_CLIENT is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:52 - root - WARNING - Warning: Optional environment variable LOG_LEVEL is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:52 - root - WARNING - Warning: Optional environment variable LOG_FILE is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:52 - root - WARNING - Warning: Optional environment variable QUEUE_NAME is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:52 - root - WARNING - Warning: Optional environment variable QUEUE_HOST is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:52 - root - WARNING - Warning: Optional environment variable QUEUE_PORT is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:52 - root - WARNING - Warning: Optional environment variable QUEUE_VHOST is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:52 - root - WARNING - Warning: Optional environment variable QUEUE_USERNAME is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:52 - root - WARNING - Warning: Optional environment variable QUEUE_PASSWORD is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:52 - root - WARNING - Warning: Optional environment variable HOST is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:52 - root - WARNING - Warning: Optional environment variable PORT is not set - env_checker.py - 26 - check_env_vars
03-Jun-23 00:00:52 - root - INFO - Using queue client rabbitmq - queue_client.py - 145 - get_client
03-Jun-23 00:00:52 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('::1', 5672, 0, 0) - connection_workflow.py - 179 - start
03-Jun-23 00:00:52 - pika.adapters.utils.io_services_utils - ERROR - Socket failed to connect: <socket.socket fd=10, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 59186, 0, 0)>; error=61 (Connection refused) - io_services_utils.py - 349 - _on_writable
03-Jun-23 00:00:52 - pika.adapters.utils.connection_workflow - ERROR - TCP Connection attempt failed: ConnectionRefusedError(61, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0)) - connection_workflow.py - 375 - _on_tcp_connection_done
03-Jun-23 00:00:52 - pika.adapters.utils.connection_workflow - ERROR - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(61, 'Connection refused') - connection_workflow.py - 291 - _report_completion_and_cleanup
03-Jun-23 00:00:52 - pika.adapters.utils.connection_workflow - INFO - Pika version 1.3.2 connecting to ('127.0.0.1', 5672) - connection_workflow.py - 179 - start
03-Jun-23 00:00:52 - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 59187), raddr=('127.0.0.1', 5672)> - io_services_utils.py - 345 - _on_writable
03-Jun-23 00:00:52 - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x107706140>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x107706140> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>). - connection_workflow.py - 428 - _on_transport_establishment_done
03-Jun-23 00:00:52 - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x107706140> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 293 - _report_completion_and_cleanup
03-Jun-23 00:00:52 - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x107706140> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - connection_workflow.py - 725 - _report_completion_and_cleanup
03-Jun-23 00:00:52 - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x107706140> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>> - blocking_connection.py - 453 - _create_connection
03-Jun-23 00:00:52 - pika.adapters.blocking_connection - INFO - Created channel=1 - blocking_connection.py - 1264 - __init__
03-Jun-23 00:00:52 - root - INFO - Connected to queue todo_tickets at localhost:5672 - queue_client.py - 72 - connect
03-Jun-23 00:00:53 - root - INFO - List ID: 647367960a35139ab08f73e3, List Name: TODO - trello_client.py - 143 - get_list_id
03-Jun-23 00:01:49 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 53 - webhook
03-Jun-23 00:02:08 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 53 - webhook
03-Jun-23 00:02:13 - root - INFO - Sent ticket 64765103e674abbe18fb9e8c to queue - routes.py - 53 - webhook
